**프로미스란?**

자바스크립트의 비동기 처리를 위한 하나의 패턴을 콜백함수로 사용한다. 하지만 전통적인 콜백 패턴은 가독성이 나쁘고 비동기 처리 중 발생하는 에러의 예외 처리가 곤란하며 여러개의 비동기 처리 로직을 한꺼번에 처리하는 것도 한계가있다. es6에서 비동기 처리를 위한 또다른 패턴이 프로미스를 도입하였다. 이는 전통적인 콜백 패텅이 가진 단점은 보완하며 비동기 시점을 명확하게 표현한다.

**콜백 패턴의 시점**
**콜백헬****
자바스크립에서 빈번하게 사용되는 비동기식 처리모델은 요청을 병렬로 처리하여 다른 요청이 블로킹되지 않는 장점이 있따.
하지만 비동기 처리를 위해 콜백패턴을 사용하면 처리 순서를 보장하기 위해 여러개의 콜백함수가 중첩되어 복잡도가 높아지는 콜백헬이 발생할수있다. 콜백헬은 가독성을 떨어뜨리고 실수를 증가시키는 원인이 된다. 

~~~ javascript
step1(function(value1) {
  step2(value1, function(value2) {
    step3(value2, function(value3) {
      step4(value3, function(value4) {
        step5(value4, function(value5) {
            // value5를 사용하는 처리
        });
      });
    });
  });
});
~~~

콜백 헬이 발생하는 이유에 대해 생각해 보자 .비동기 처리 모델은 실행완료를 기다리지않고 즉시다음 태스크를 기다리지않고  실시한다. 따라서 비동기 함수(비동기를 처리하는 함수)내에서 결과를 반환(또는 전역변수의 할당)하면 기대한 대로 동작하지않는다.



~~~javascript
<!DOCTYPE html>
<html>
<body>
  <script>
    // 비동기 함수
    function get(url) {
      // XMLHttpRequest 객체 생성
      const xhr = new XMLHttpRequest();

      // 서버 응답 시 호출될 이벤트 핸들러
      xhr.onreadystatechange = function () {
        // 서버 응답 완료가 아니면 무시
        if (xhr.readyState !== XMLHttpRequest.DONE) return;

        if (xhr.status === 200) { // 정상 응답
          console.log(xhr.response);
          // 비동기 함수의 결과에 대한 처리는 반환할 수 없다.
          return xhr.response; // ①
        } else { // 비정상 응답
          console.log('Error: ' + xhr.status);
        }
      };

      // 비동기 방식으로 Request 오픈
      xhr.open('GET', url);
      // Request 전송
      xhr.send();
    }

    // 비동기 함수 내의 readystatechange 이벤트 핸들러에서 처리 결과를 반환(①)하면 순서가 보장되지 않는다.
    const res = get('http://jsonplaceholder.typicode.com/posts/1');
    console.log(res); // ② undefined
  </script>
</body>
</html>
~~~



1.get함수 2.xhr.open 3.xhr.send 4.conole.log(res) 5.readyonchange  이벤트핸들러 순서로 처리된다. 이벤트 핸들러는 태스크 큐에 들어가있다가 콜 스택이 비어야 호출되므로 console.log 호출 시점이전에 이미 발생했더라도 get함수가 정료되면 곧바로 console.log가 호출되기 때문에  console.log가 콜스택에서 제거된후에 redystatechange는 실행된다.

 즉, 비동기 함수의 처리 결과를 반환하는 경우, 순서가 보장되지 않기 때문에 그 반환 결과를 가지고 후속 처리를 할 수 없다. 즉, 비동기 함수의 처리 결과에 대한 처리는 비동기 함수의 콜백 함수 내에서 처리해야 한다. 이로 인해 콜백 헬이 발생한다.

만일 비동기 함수의 처리 결과를 가지고 다른 비동기 함수를 호출해야 하는 경우, 함수의 호출이 중첩(nesting)이 되어 복잡도가 높아지는 현상이 발생하는데 이를 **Callback Hell**이라 한다.

Callback Hell은 코드의 가독성을 나쁘게 하고 복잡도를 증가시켜 실수를 유발하는 원인이 되며 **에러 처리가 곤란**하다.

**에러 처리의 한계**

~~~ javascript
try{
  setTimeout(()=>{throw new Error('error!');},1000);
}catch{
  console.log('에러를 차지 못하였습니다.');
  console.log(e);
}
~~~

비동기 처리 함수의 콜백 함수는 해당 이벤트(timer 함수의 tick 이벤트, XMLHttpRequest의 readystatechange 이벤트 등)가 발생하면 태스트 큐(Task queue)로 이동한 후 호출 스택이 비어졌을 때, 호출 스택으로 이동되어 실행된다. setTimeout 함수는 비동기 함수이므로 콜백 함수가 실행될 때까지 기다리지 않고 즉시 종료되어 호출 스택에서 제거된다. 이후 tick 이벤트가 발생하면 setTimeout 함수의 콜백 함수는 태스트 큐로 이동한 후 호출 스택이 비어졌을 때 호출 스택으로 이동되어 실행된다. 이때 setTimeout 함수는 이미 호출 스택에서 제거된 상태이다. 이것은 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다라는 것을 의미한다. setTimeout 함수의 콜백 함수의 호출자(caller)가 setTimeout 함수라면 호출 스택에 setTimeout 함수가 존재해야 하기 때문이다.

예외(exception)는 호출자(caller) 방향으로 전파된다. 하지만 위에서 살펴본 바와 같이 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니다. 따라서 setTimeout 함수의 콜백 함수 내에서 발생시킨 에러는 catch 블록에서 캐치되지 않아 프로세스는 종료된다.

이러한 문제를 극복하기 위해 [Promise](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise)가 제안되었다. Promise는 ES6에 정식 채택되어 **IE를 제외한** 대부분의 브라우저가 지원하고 있다.

**프로미스의 생성**

프미스는 프로미스 생성자 함수를 통해서 인스턴스화 한다. promise 생성자 함수는 비동기 작업을 수행할 콜백 함수를 인자로 전달 받는데 이 콜백 함수는 resolve와 react함수를 인자로 받는다.

~~~javascript
const promise new Promise((resolve,react)=>{
  if(비동기 작업 수행){
    resolve('result');
  }else{//비동기 작업 수행 실패
    reject('failure reason');
  }
})
~~~

promise는 비동기 처리가 성공하였는지 실패하였는지 등의 상태 정보를 갖는다.
 

| 상태          | 의미                                       | 구현                                               |
| :------------ | :----------------------------------------- | :------------------------------------------------- |
| pending       | 비동기 처리가 아직 수행되지 않은 상태      | resolve 또는 reject 함수가 아직 호출되지 않은 상태 |
| **fulfilled** | 비동기 처리가 수행된 상태 (성공)           | resolve 함수가 호출된 상태                         |
| **rejected**  | 비동기 처리가 수행된 상태 (실패)           | reject 함수가 호출된 상태                          |
| settled       | 비동기 처리가 수행된 상태 (성공 또는 실패) | resolve 또는 reject 함수가 호출된 상태             |

Promise 생성자 함수가 인자로 전달받은 콜백 함수는 내부에서 비동기 처리 작업을 수행한다. 이때 비동기 처리가 성공하면 콜백 함수의 인자로 전달받은 resolve 함수를 호출한다. 이때 프로미스는 ‘fulfilled’ 상태가 된다. 비동기 처리가 실패하면 reject 함수를 호출한다. 이때 프로미스는 ‘rejected’ 상태가 된다. Promise를 사용하여 비동기 함수를 정의해보자.

~~~javascript
const promiseAjax = (method, url, payload) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open(method, url);
    xhr.setRequestHeader('Content-type', 'application/json');
    xhr.send(JSON.stringify(payload));

    xhr.onreadystatechange = function () {
      // 서버 응답 완료가 아니면 무시
      if (xhr.readyState !== XMLHttpRequest.DONE) return;

      if (xhr.status >= 200 && xhr.status < 400) {
        // resolve 메소드를 호출하면서 처리 결과를 전달
        resolve(xhr.response); // Success!
      } else {
        // reject 메소드를 호출하면서 에러 메시지를 전달
        reject(new Error(xhr.status)); // Failed...
      }
    };
  });
~~~

**프로미스의 후속처리 메소드**
Promise로 구현된 비동기 함수는 Promise 객체를 반환하여야 한다. Promise로 구현된 비동기 함수를 호출하는 측(promise consumer)에서는 Promise 객체의 후속 처리 메소드(then, catch)를 통해 비동기 처리 결과 또는 에러 메시지를 전달받아 처리한다. Promise 객체는 상태를 갖는다고 하였다. 이 상태에 따라 후속 처리 메소드를 체이닝 방식으로 호출한다.then

then 메소드는 두 개의 콜백 함수를 인자로 전달 받는다. 첫 번째 콜백 함수는 성공(fulfilled, resolve 함수가 호출된 상태) 시 호출되고 두 번째 함수는 실패(rejected, reject 함수가 호출된 상태) 시 호출된다.
**then 메소드는 Promise를 반환한다.**catch

예외(비동기 처리에서 발생한 에러와 then 메소드에서 발생한 에러)가 발생하면 호출된다. catch 메소드는 Promise를 반환한다.catch

**프미스의 에러 처리**

비동기 함수 get은 Promise 객체를 반환한다. Promise 객체의 후속 처리 메소드를 사용하여 비동기 처리 결과에 대한 후속 처리를 수행한다. 비동기 처리 시 발생한 에러 메시지는 then 메소드의 두 번째 콜백 함수로 전달된다. Promise 객체의 후속 처리 메소드 catch을 사용하여도 에러를 처리할 수 있다.

catch 메소드는 에러를 처리한다는 점에서 then 메소드의 두 번째 콜백 함수와 유사하지만 미묘한 차이가 있다. then 메소드의 두 번째 콜백 함수는 비동기 처리에서 발생한 에러(reject 함수가 호출된 상태)만을 캐치한다. 하지만 catch 메소드는 비동기 처리에서 발생한 에러(reject 함수가 호출된 상태)뿐만 아니라 then 메소드 내부에서 발생한 에러도 캐치한다. 따라서 에러 처리는 catch 메소드를 사용하는 편이 보다 효율적이다.

**프로미스 체이닝**

Promise 객체를 반환한 비동기 함수는 프로미스 후속 처리 메소드인 then이나 catch 메소드를 사용할 수 있다. 따라서 then 메소드가 Promise 객체를 반환하도록 하면(then 메소드는 기본적으로 Promise를 반환한다.) 여러 개의 프로미스를 연결하여 사용할 수 있다.

**프미스의 정적메소드**
프로미스는 주로 생성자 함수로 호출되지만 함수도 객체이므로 메소드를 가질수있다. 프로미스 객체는 4가지 정적메소드를 제공한다.

**promise.resolve/promise.reject**
존재하는  promise 의 값을 래핑하기위해 사용한다. 정적메소드 promise.resolve메소드는 인자로 전달된 값을 resolve하는  promise을 반환한다.

~~~javascript
const resolvePromise=Promise.resolve([1,2,3]);
resolvePromise.then(console.log);//[1,2,3];
~~~

위 예제는 아래와 동일하게 동작한다.

~~~javascript
const resolvePromise = new Promise(resolve=>resolve([1,2,3]));
resolvePromise.then(console.log)//[1,2,3];
~~~

Promise.reject 메소드는 인자로 전달된 값을 reject하는 프로미스를 생성한다.

~~~javascript
const rejectPromise = Promise.reject(new Error('Error'));
rejectPromise.catch(console.log);//Error: Error!
~~~

**promise.all** 

메소드에 담겨있는 배열등의 이터러블을 인자로 전달받는다.그리고 전달 받은 모든 프로미스를 병렬처리하고 그 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

~~~javascript
Promise.all([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
]).then(console.log) // [ 1, 2, 3 ]
  .catch(console.log);
]
~~~

메소드는 3개의 프로미스를 담은 배열을 전달받았다. 첫번째 프로미스는 3초 후에 1을 resolve하여 처리결과를 반환한다.
두뻔째 프로미스는 2초 후에 2을 resolve하여 처리결과를 반환한다. 세번째 프로미스는 1초 후에 3을 resolve하여 처리는 반환한다. promise.all메소드는 전달받은 모든 프로미스들을 병렬로 처리한다. 이때 모든ㄷ 프로미스의 처리가 종료될때 까지 기다린 후에  모든 결과를 resolov 또는 reject한다.
모든 프로미스가 처리가 성고하면 각각의 프로미스가 resolve한 처리 결과를 배열에 담아 resolve 하는 새료운 배열을 반환한다. 그리고 처리순서가 보장된다.
프로미스의 처리가 하나라도 실패하면 가장 먼저 실패한 프로미스가 reject 한 에러를 reject하는 새로운 프로미스르반환한다.

~~~javascript
Promise.all([
   new Promise((resolve,reject))=?setTimeout(()=>reject(new Error('Error 1!')),3000),
   new Promise((resolve,reject))=?setTimeout(()=>reject(new Error('Error 2!')),2000),
   new Promise((resolve,reject))=?setTimeout(()=>reject(new Error('Error 3!')),1000),
]).then(console.log)
	.catch(consoel.log)//Error: Error 3;
 

~~~

 위 예제의 경우 세번째 프로미스가 가장 먼저 실패하기 때문에 세번째 프로미스가 reject한 에러가 catch메소드로 전달된다. Promise/all메소드는 전달 받은 이터러블의 요소가 프로미스가 아닌 경우,promise.resolve메소드를 통해 프로미스로 래핑된다.

~~~javascript
Promise.all([
  1,//promise.resolve(1)
  2,//promise.resolve(2)
  3,//promise.resolve(3)
]).then(console.log);
	.catch(console.log);
~~~

~~~javascript
const githubIds=['kim','jae,''hun];
Promise.all([githubIds.map(id=>fetch(`htt;://api.github.com/users/${id}`))])
.then(responses=>Promise.all(responses.map(res=>res.json())))
.then(users=>users.map(users.map(user=>user.name)))
.then(console.log)
.catch(console.log);
~~~

위 예제의 Promise.all 메소드는 fetch 함수가 반환한 3개의 프로미스의 배열을 인수로 전달받고 이 프로미스들을 병렬 처리한다. 모든 프로미스의 처리가 성공하면 Promise.all 메소드는 각각의 프로미스가 resolve한 3개의 Response 객체가 담긴 배열을 resolve하는 새로운 프로미스를 반환하고 후속 처리 메소드 then에는 3개의 Response 객체가 담긴 배열이 전달된다. 이때 json 메소드는 프로미스를 반환하므로 한번 더 Promise.all 메소드를 호출해야 하는 것에 주의하자. 두번째 호출한 Promise.all 메소드는 github로 부터 취득한 3개의 사용자 정보 객체가 담긴 배열을 resolve하는 프로미스를 반환하고 후속 처리 메소드 then에는 3개의 사용자 정보 객체가 담긴 배열이 전달된다.


**promise.race****

promise.race메소드는 promise.all 메소드와 동일하게 프로미스에 담겨있는 배열 등의 이터러블을 인자로 전달 받는다. 그리고 promise.race메소드는 promise.all메소드 처럼 모든 프로미스를 병렬처리하는 것이 아니라 가장 먼저 처리된 프로미스가 resolve  한 처리 결과를 resolve 하는 새로운 프로미스를 반환한다.

~~~javascript
Promise.race([
  new Promise(resolve=>setTimeout(()=>resolve(1),3000)),//1
	new Promise(resolve=>setTimeout(()=>resolve(2),2000)),//2
	new Promise(resolve=>setTimeout(()=>resolve(3),1000))//3
]).then(console.log)//3
	.catch(console.log);
~~~

에러가 발생한 경우 promise.all 메소드와 동일하게 처리된다. 즉 promise.race 메소드에 전달된 프로미스 처리가 하나라도 실패하면 가장 먼저 실패한 프로미스가 reject한 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

~~~javascript
Promise.race([
  new Promise((resolve,reject)=>setTimout(()=> reject(new Error('Error1')),3000)),//3
  new Promise((resolve,reject)=>setTimeout(()=>reject(new Error('Error2')),2000)),//2
  new Promise((resolve,reject)=>setTimeout(()=>reject(new Error('Error3')),1000))//1
]).then(console.log)
	.catch(console.log)//Error: Error3
~~~

